### ISSUE TITLE
Rsponse status code does not indicate success: 403

### ISSUE THREAD

**Issue by lyssieth** [erraineon/E621Client#1]
I'm getting 403 codes whenever trying to use this. The code is:

```cs
        public async Task<E621Post> Random(params string[] fullTags) {
            var tags = fullTags.Select(x => x.ToLower());
            var client = new E621Client(UserAgent);

            try {
                var posts = await client.Search(new E621SearchOptions {
                    Tags = ("order:random " + string.Join(" ", tags)).Trim(),
                    Limit = 1
                });

                return posts.First();
            } catch (Exception e) {
                SimpleLog.GetLog("UnsafeService/E621").Warn(e);
                return null;
            }
        }
```

and the error is
```
[21:10:42 18.03.2020] [Warning] [UnsafeService/E621]: System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at E621.E621Client.Request(String requestUri)
   at E621.E621Client.Search(E621SearchOptions options)
   at Epsilon.Services.E621.Random(String[] fullTags) in UnsafeService.cs:line 53
```

**Comment by lyssieth** [comment]
[BooruSharp](https://github.com/Xwilarg/BooruSharp) is a better solution.
